### ISSUE TITLE
gitlib-cmdline on stackage?

### ISSUE THREAD

**Issue by mstksg** [jwiegley/gitlib#62]
Any particular reason why gitlib-cmdline is not on stackage?  I noticed that gitlib, gitlib-libgit2, and gitlib-test were on there.

**Comment by jwiegley** [comment]
None that I know of. I don't pay attention to stackage, so I'm not the one who decided that.

**Comment by mstksg** [comment]
Ah okay, thanks.  It looks like @borsboom is maintaining gitlib-libgit2 for stackage purposes, I see now.  Thanks for the response!

**Comment by borsboom** [comment]
I just added gitlib-libgit2 because I needed it there.  @mstksg feel free to add gitlib-cmdline to Stackage yourself, it just means that you'll be the contact point if there are any stackage-related issues with the package.
