### ISSUE TITLE
Diff of two trees

### ISSUE THREAD

**Issue by cuklev** [jwiegley/gitlib#71]
Hi,
Is it currently possible to take the diff ot two `Tree`s? As far I can tell `c'git_diff_tree_to_tree` is not used anywhere.

**Comment by jwiegley** [comment]
Sounds like something that simply needs to be added to the surface API, and then matched in the cmdline and libgit2 backends.

**Comment by cuklev** [comment]
I am gonna work on a Pull request in the days ahead. That is, if you are not plannig to add it yourself.

**Comment by jwiegley** [comment]
Go for it! I won't be touching gitlib anytime in the immediate future.

**Comment by tuncer** [comment]
@cuklev, any updates?

**Comment by cuklev** [comment]
Not really. I remember looking at the `git_diff_foreach` function and that it's parameters had changed in newer libgit2. So, I have put this aside.

**Comment by tuncer** [comment]
@cuklev, does that mean you're waiting for gitlib to sync with a newer libgit2?

**Comment by shinzui** [comment]
Is it still impossible to diff two trees?

**Comment by m-col** [comment]
I'd also like this so figured I'd try my hand at implementing it. I've got a small amount of distance quite slowly so figured I'd see if there is guidance available. This is my change so far:
```diff
diff --git a/gitlib-libgit2/Git/Libgit2.hs b/gitlib-libgit2/Git/Libgit2.hs
index 1ab46a4..768e3af 100644
--- a/gitlib-libgit2/Git/Libgit2.hs
+++ b/gitlib-libgit2/Git/Libgit2.hs
@@ -390,6 +390,29 @@ lgSourceTreeEntries (LgTree (Just tree)) = gatherFrom' 16 $ \queue -> do
             writeTBQueue queue $ name `seq` entry `seq` (name,entry)
         return 0
 
+lgDiffTreeToTree
+    :: (MonadLg m, HasLgRepo m)
+    => Tree
+    -> Tree
+    -> Int  -- git_diff_options
+    -> m (Maybe Text)
+lgDiffTreeToTree (LgTree Nothing) _ _ = return ()
+lgDiffTreeToTree _ (LgTree Nothing) _ = return ()
+lgDiffTreeToTree (LgTree tree1) (LgTree tree2) options =
+    withForeignPtr tree1 \ptr1 ->
+        withForeignPtr tree2 \ptr2 -> alloca $ \diffPtr ->
+            repo <- getRepository
+            r <- c'git_diff_tree_to_tree diffPtr ptr1 ptr2 nullPtr
+            if r < 0
+                then return Nothing
+                else do
+                    r <- c'git_diff_foreach diffPtr file_cb nullPtr nullPtr nullPtr
+                    if r < 0
+                        then return Nothing
+                        else
+  where
+    -- file_cb :: Ptr (<git_diff_delta>) -> CFloat -> Ptr () -> IO CInt
+
 lgMakeBuilder :: (MonadLg m, HasLgRepo m)
               => ForeignPtr C'git_treebuilder -> TreeBuilder m
 lgMakeBuilder builder = Git.TreeBuilder
```
The question is what should this function actually give you or do. I was thinking either it could accept a callback and use that where `file_cb` is above, working out something to do at the next stage which would then involve the `git_diff_delta`s. Or maybe just convert deltas etc into (a source of) strings and return that. Thoughts?

**Comment by jwiegley** [comment]
I'd probably go with the callback, since that allows for efficient operation and the caller can I always use a callback the aggregates some result value, if that's what they need.

**Comment by m-col** [comment]
Cool, so for the linked PR, I can drop the 3 callback functions implemented there, instead accepting functions with their signatures as inputs to the main function, and then because the types added to `Git.Types` become redundant I can drop those too. Users can define their own types according to the logic in their callback functions. Does that sound good?

**Comment by jwiegley** [comment]
Sounds good!
