### ISSUE TITLE
Tutorial.hs seems out of date

### ISSUE THREAD

**Issue by I3ck** [jwiegley/gitlib#81]
The tutorial within Tutorial.hs seems to be out of date.  
I also couldn't find any snippets showing how to open a Repo from a given path.  
This makes it really difficult to get started.

**Comment by jwiegley** [comment]
For now, look at `git-monitor` as an example of using the library. The most common way to open a repository is:

```
withRepository <factory> <path> $ do ...
```

**Comment by camelpunch** [comment]
FWIW I'm finding [the tests](https://github.com/jwiegley/gitlib/blob/master/gitlib-test/Git/Smoke.hs) a bit easier to read than git-monitor. Sample commits etc.
